apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: big-project # ‡∏£‡∏±‡∏ô‡πÉ‡∏ô‡∏´‡πâ‡∏≠‡∏á‡∏ó‡∏µ‡πà‡πÄ‡∏£‡∏≤‡πÄ‡∏û‡∏¥‡πà‡∏á‡∏™‡∏£‡πâ‡∏≤‡∏á
spec:
  replicas: 2 # ‡∏£‡∏±‡∏ô‡πÅ‡∏≠‡∏õ‡∏û‡∏£‡πâ‡∏≠‡∏°‡∏Å‡∏±‡∏ô 2 ‡∏Å‡πä‡∏≠‡∏õ‡∏õ‡∏µ‡πâ
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: mosuthecreator/go-app:v1 # ‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô‡πÄ‡∏õ‡πá‡∏ô ID ‡∏Ç‡∏≠‡∏á‡∏Ñ‡∏∏‡∏ì
        workingDir: /app  # üëà ‡πÄ‡∏û‡∏¥‡πà‡∏°‡∏ö‡∏£‡∏£‡∏ó‡∏±‡∏î‡∏ô‡∏µ‡πâ‡πÄ‡∏Ç‡πâ‡∏≤‡πÑ‡∏õ (‡∏ï‡πâ‡∏≠‡∏á‡∏ï‡∏£‡∏á‡∏Å‡∏±‡∏ö WORKDIR ‡πÉ‡∏ô Dockerfile)
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "db" # ‡∏ä‡∏∑‡πà‡∏≠‡πÄ‡∏î‡∏µ‡∏¢‡∏ß‡∏Å‡∏±‡∏ö Service ‡∏Ç‡∏≠‡∏á Postgres ‡∏Ç‡πâ‡∏≤‡∏á‡∏ö‡∏ô
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "url_db"
        - name: API_KEY
          value: "bruh1234"
